name: vorfast_design_system_module
description: Modulo responsável pelo gerenciamento da UI
publish_to: 'none'
version: 0.0.0+1
homepage: https://github.com/pwlimaverde/vorfast/tree/master/modulos/vorfast_design_system_module

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  dependency_module:
    path: ../dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
