name: auth_google_package
description: Package para autenticação de usuario usando as apis do Google.
publish_to: 'none'
version: 1.0.0
homepage:

environment:
  sdk: ">=2.14.3 <3.0.0"
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  dependency_module:
    path: ../../modulos/dependency_module

dev_dependencies:
  rxdart: ^0.26.0
  mocktail: ^0.0.1-dev.12
  flutter_test:
    sdk: flutter
    
flutter: