name: app_client_vorfast_loja1
description: App client loja 1 vorfast
publish_to: 'none' 
version: 0.0.0-alpha.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_module:
    path: ../modulos/dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true